spring:
    elasticsearch:
        uris: "http://0.0.0.0:9200"
        username: "elastic"
        password: "dilanka-rathnasiri"
        connection-timeout: 5s
csv:
    path: "../dataset/processed_data.csv"
